spring:
  application:
    name: week14_todoapp

  datasource:
    url: jdbc:mysql://lion-db.c9i2u4yu40qt.ap-northeast-2.rds.amazonaws.com:3306/mydatabase
    username: ${DB_USERNAME}  # run config 환경 변수로 설정
    password: ${DB_PASSWORD}  # run config 환경 변수로 설정
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect